# Generated by Django 4.2.4 on 2023-08-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='accounts.level'),
        ),
        migrations.AddField(
            model_name='student',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='section_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
