# Generated by Django 4.2.4 on 2023-08-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='college_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
